databases:
    - name: maydayhelpdeskapi
      databaseName: maydayhelpdeskapi
      user: maydayhelpdeskapi
      plan: free

services:
    - type: web
      name: maydayhelpdeskapi
      runtime: ruby
      plan: free
      buildCommand: './bin/render-build.sh'
      # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
      startCommand: './bin/rails server'
      # startCommand: "bundle exec rails server"
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: maydayhelpdeskapi
                property: connectionString
          - key: RAILS_MASTER_KEY
            sync: false
          - key: WEB_CONCURRENCY
            value: 2 # sensible default